services:
  app:
    image: deampuleadd/custom-base:test
    platform: linux/arm64
    volumes:
      - app-data:/var/www/html/volume
      - app-images:/var/www/html/public/images
    command: >
      sh -c "rsync -a --delete --exclude='public/images/' /var/www/html/laravel/ /var/www/html/volume"
  php-fpm:
    image: deampuleadd/custom-base:test
    platform: linux/arm64
    depends_on:
      - app
    volumes:
      - app-data:/var/www/html/laravel
      - app-images:/var/www/html/public/images
    restart: always
    command: php-fpm

  nginx:
    image: deampuleadd/custom-nginx:test
    platform: linux/arm64
    depends_on:
      - app
      - php-fpm
    volumes:
      - app-data:/var/www/html/laravel
    ports:
      - "80:80"
    restart: always

  mysql:
    image: mysql:latest
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: admin_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: deampuleadd/custom-redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /home/redis-persist:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  php-cli-worker:
    image: deampuleadd/custom-phpcli:latest
    depends_on:
      - redis
      - app
    volumes:
      - app-data:/var/www/html/laravel
    command: php artisan queue:work redis --sleep=1 --tries=3
    restart: unless-stopped

  reverb:
    image: deampuleadd/custom-phpcli:latest
    depends_on:
      - php-fpm
      - redis
    ports:
      - "6001:6001"
    volumes:
      - app-data:/var/www/html/laravel
    command: php artisan reverb:start

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_SKIP_USER_MANAGEMENT=true
      - N8N_LICENSE_KEY=your-license-key
      - N8N_AUTH_EXCLUDE_ENDPOINTS=rest/workflows
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/workflows
      - ./init.sh:/init.sh
    entrypoint: ["/bin/sh", "/init.sh"]

volumes:
  app-data:
  app-images:
  mysql_data:
  n8n_data: